config/routes.rb
Rails.application.routes.draw do

  mount CookV1Api => '/api/v1'

  resources :s_subsyst_lists
  get 'user_subsyst_list' => 's_subsyst_lists#user_subsys'
  resources :sessions, only:[:new, :create, :destroy]
  resources :d_login_msgs do
    get "region_codes", on: :collection
  end

  resources :s_role_msgs 
  
  resources :ihomes

  resources :d_notice_msgs

  resources :d_login_ips #限制登陆IP

  resources :s_region_code_infos do
    get "get_ids", on: :collection
  end

  resources :windy

  resources :root_home

  resources :s_system_configs

  get "GIS_map" => "gis_map#index"

  root 'ihomes#index'

end

app/models/s_role_msg.rb
class SRoleMsg < ActiveRecord::Base
  has_many :s_role_funcs
  # has_many :s_func_msgs, through: :s_role_funcs

  #has_many :s_role_subsysts
  #has_many :s_subsyst_lists, :through => :s_role_subsysts
  

  has_many :s_role_funcs 
  has_many :s_subsyst_list,:through => :s_role_funcs

end

app/controllers/s_role_msgs_controller.rb
class SRoleMsgsController < ApplicationController
  before_filter :authenticate_user
  before_action :set_s_role_msg, only: [:show, :edit, :update, :destroy]

  # GET /s_role_msgs
  # GET /s_role_msgs.json
  def index
    role_name = params[:role_name]
    pageNow = params[:pageNow]
    pageSize = 10   
    if @login_name.present?
      roles = SRoleMsg.all
      @s_role_msgs = roles.page(pageNow).per(pageSize)
      @count = roles.count
      s = @count%pageSize
      if s == 0
        @page = @count/pageSize
      else
        @page = (@count-s)/pageSize+1
      end
    else
      roles = SRoleMsg.where( "role_name LIKE ?", "%#{role_name}%" )
      @s_role_msgs = roles.page(pageNow).per(pageSize)
      @count = roles.count
      s = @count%pageSize
      if s == 0
        @page = @count/pageSize
      else
        @page = (@count-s)/pageSize+1
      end
    end  
    @arr = Array.new
    @s_role_msgs.each do |role|
      a1 = Array.new
      SRoleFunc.where('s_role_msg_id = ?',role.id).each do |role_func|
        a1.push SSubsystList.find(role_func.s_func_msg_id).sys_name
      end
      @arr.push a1
    end 
    Rails.logger.info @arr
  end

  # GET /s_role_msgs/1
  # GET /s_role_msgs/1.json
  def show
  end

  # GET /s_role_msgs/new
  def new
    @s_role_msg = SRoleMsg.new
    @navi_all   = SFuncMsg.where( "root_distance" => 1 ).order( "queue_index" )
  end

  # GET /s_role_msgs/1/edit
  def edit
    role_id    = params[:id]
    @s_role_msg = set_s_role_msg
    @func_code_true = @s_role_msg.s_role_funcs
  end

  # POST /s_role_msgs
  # POST /s_role_msgs.json
  def create
    @s_role_msg      = SRoleMsg.new(s_role_msg_params)
    func_code_trues  = params[:func_code_true]
    
    # 写日志
    wLoginOpr = WLoginOpr.new
    wLoginOpr.op_code   = "s_role_msgs|create"
    wLoginOpr.op_time   = Time.now.to_s
    wLoginOpr.login_no  = current_user.login_no
    wLoginOpr.ip_addr   = current_user.ip_address
    wLoginOpr.op_note   = "增加角色"
    wLoginOpr.op_describe = current_user.login_name + "：增加角色"
    
    # 新增角色时增加角色功能表
    retCode = true
    @s_role_msg.transaction do
      retCode = @s_role_msg.save! 
      unless func_code_trues.blank?
        func_code_trues.each do |func_code_true|
          s_role_func_data = SRoleFunc.new  
          s_role_func_data.s_func_msg_id = func_code_true
          s_role_func_data.s_role_msg_id = @s_role_msg.id
          retCode = s_role_func_data.save!
        end 
      end

      retCode = wLoginOpr.save! if retCode
    end

    respond_to do |format|
      if retCode
        self.index
        # render json:{'status': '新增成功'}
        # format.html { render 'index' }
        format.json { render json:{'status': '新增成功'}}
      else
        format.html { render :new }
        format.json { render json: @s_role_msg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /s_role_msgs/1
  # PATCH/PUT /s_role_msgs/1.json
  def update
    role_id          = params[:id]
    valid_flag       = params[:valid_flag]
    func_code_trues  = params[:func_code_true]
    func_code_falses = params[:func_code_falses]
    s_role_funcs     = SRoleFunc.all
    Rails.logger.debug( "初始化: " + func_code_trues.to_s)
    Rails.logger.debug( "初始化: " + func_code_falses.to_s)
    ### 插入新增的权限功能
    unless func_code_trues.blank?
      func_code_trues.each do |func_code_true|
        is_has = false

        s_role_funcs.each do |s_role_func|  
          if func_code_true.to_i == s_role_func.s_func_msg_id && role_id.to_i == s_role_func.s_role_msg_id
            is_has = true
            break
          else 
            next
          end
        end  
        if !is_has
          s_role_func_data = SRoleFunc.new  
          s_role_func_data.s_func_msg_id = func_code_true
          s_role_func_data.s_role_msg_id = role_id  
          s_role_func_data.save
        end
      end
    end
      
    #### 删除取消的权限功能
    Rails.logger.info func_code_falses
    unless func_code_falses.blank?
      s_role_funcs.each do |s_role_func|    
        func_code_falses.each do |func_code_false|
          if func_code_false.to_i == s_role_func.s_func_msg_id && role_id.to_i == s_role_func.s_role_msg_id
            s_role_funcs.find_by( "s_func_msg_id = ? and s_role_msg_id = ?",func_code_false,role_id ).destroy        
          end
        end 
      end
    end 

    # 写日志
    wLoginOpr = WLoginOpr.new
    wLoginOpr.op_code   = "s_role_msgs|update"
    wLoginOpr.op_time   = Time.now.to_s
    wLoginOpr.login_no  = current_user.login_no
    wLoginOpr.ip_addr   = current_user.ip_address
    wLoginOpr.op_note   = "编辑角色权限"
    wLoginOpr.op_describe = current_user.login_name + "：编辑角色权限"
    
    respond_to do |format|
      if @s_role_msg.update(s_role_msg_params)
        wLoginOpr.save
        self.index
        format.html { render 'index' }
        format.json { render :show, status: :ok, location: @s_role_msg }
      else
        format.html { render :edit }
        format.json { render json: @s_role_msg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /s_role_msgs/1
  # DELETE /s_role_msgs/1.json
  def destroy
    @s_role_msg.destroy
    respond_to do |format|
      format.html { redirect_to s_role_msgs_url, notice: 'S role msg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_s_role_msg
      @s_role_msg = SRoleMsg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def s_role_msg_params
      params.require(:s_role_msg).permit(:role_name, :valid_flag, :root_distance, :queue_index)
    end
end

app/views/s_role_msgs/_form.html.erb
<div class="roleNew">
	<%= form_for(@s_role_msg) do |f| %>
	  <% if @s_role_msg.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@s_role_msg.errors.count, "error") %> prohibited this s_role_msg from being saved:</h2>

		  <ul>
		  <% @s_role_msg.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>

	  <div class="field">
		<%= f.label :role_name %>
		<%= f.text_field :role_name %>
	  </div>
	  <div class="field">
		<%= f.label :valid_flag %>
		<%= f.text_field :valid_flag %>
	  </div>
	  <div class="field">
		<%= f.label :root_distance %>
		<%= f.number_field :root_distance %>
	  </div>
	  <div class="field">
		<%= f.label :queue_index %>
		<%= f.number_field :queue_index %>
	  </div>
	  <div class="actions">
		<%= f.submit %>
	  </div>
	<% end %>
</div>

app/views/s_role_msgs/edit.html.erb
<div id="manage">
	<div class="content">
		<div class="content-outside">
			<%= form_for(@s_role_msg,method:'put') do |f| %>
				<% if @s_role_msg.errors.any? %>
					<div id="error_explanation">
					  <h2><%= pluralize(@s_role_msg.errors.count, "error") %> prohibited this s_role_msg from being saved:</h2>

					  <ul>
					  <% @s_role_msg.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					  <% end %>
					  </ul>
					</div>
				<% end %>
				<p>角色编辑</p>
				<div class="content-inside">
					<div class="line-top">
						<p>请选择以下表单</p>
					</div>
					<div class="line roleName" >
						<span>角色名称</span>
						<%= f.text_field :role_name,required:"true",readonly:"true" %>
					</div>
					<div class="line">
						<span>是否启用</span>
						<a href="javascript:">
							<b class="hide"><%= @s_role_msg.valid_flag %></b>
							<span class="right-radio">
								<%= f.radio_button "valid_flag","1",id:"optionsRadios1",checked:"checked" %>是
							</span>
							<span class="right-radio">
								<%= f.radio_button "valid_flag","0",id:"optionsRadios2",checked:"checked" %>否
							</span>
						</a>
					</div>
					<div class="line">
						<div class="line-top">
							<p>权限选项</p>
						</div>
					</div>
					<ul class="left-list list">
						<% @navi_all.each do |navi_all| %>
						<li class="che1 che">
							<p>
							   <input type="checkbox" <%= :checked if check_bar_in_all(navi_all.func_code) %> />
							   <span><%= navi_all.func_name %></span>
							   <i><%= navi_all.id %></i>
							</p>
							<ul>
								<% navi_all.son_funcs.each do |all_son_funcs| %>
									<li>
										<input type="checkbox" <%= :checked if check_func_in_all(all_son_funcs.func_code) %> />
										<%= all_son_funcs.func_name %>
										<i><%= all_son_funcs.id %></i>
									</li>
								<% end %>
							</ul>
						</li>
						<% end %>
					</ul>
				</div>
				<%= f.text_field "role_name",{name:"func_code_true",class:"showId hide"} %>
				<%= f.text_field "role_name",{name:"func_code_false",class:"hideId hide"} %>
				<%= f.submit "提交",class:"btn btn-primary roleSubmit"%>
			<% end %>	
		</div>
	</div>
</div>
<script>
$(function(){
	/*是否启用*/
	if($("#manage .line .hide").html() == 1){
		$("#optionsRadios1").prop("checked","checked");
		$("#optionsRadios2").removeAttr("checked");
	}
	if($("#manage .line .hide").html() == 0){
		$("#optionsRadios2").prop("checked","checked");
		$("#optionsRadios1").removeAttr("checked");
	}
	/*提交id*/
	$(".roleSubmit").click(function(){
		var showid = [];
		var hideid = [];
		for(var f=0;f<$(".che input").length;f++ ){
			if($('.che input')[f].checked == true){
				showid.push($(".che i")[f].innerHTML);
				$('.showId').val(showid);
			}else{
				hideid.push($(".che i")[f].innerHTML);
				$('.hideId').val(hideid);
			}
		}
		console.log(showid);
		console.log(hideid);
	});
	$('.list > li>p>span').click(function(){
		$(this).parent().siblings().toggle().end().parents('li').siblings().find('ul').hide()
	})
	$('#manage .list .che p input').click(function(){
		$(this).parents('.che').find('ul li input').prop('checked',this.checked);
	})
	$('#manage .list .che ul li input').click(function(){
		$(this).parents('.che').find('p > input').prop('checked',this.checked)
	})
	$("#optionsRadios2").click(function(){
		$(".che input").attr('disabled',"true");
		$(".che input").removeAttr('checked');
	});
	$("#optionsRadios1").click(function(){
		$(".che input").removeAttr('disabled');
		$(this).parents(".content-inside").find($(".che input")).prop('checked',this.checked);
	});
})	
</script>	

app/views/s_role_msgs/index.html.erb
<%  content_for :javascript do javascript_include_tag "#{controller_name}" end %>
<style>
    body{
        background:#f5f5f5;
    }
</style>
<div id="role_limit">
    <small class="session hide"><%= @current_user.session %></small>
    <div class="container">
        <div class="col-lg-3 col-md-3 col-sm-3 newsLeft">
           <div class="title">
                <span class="goodBack"></span>
                应用权限
           </div>
            <div class="newRole banner cursorPointer" data-toggle="modal" data-target="#limit_add">
                <div class="radius">
                   <img src="<%= image_path("add.png")%>" />
                </div>
                创建角色
            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-9 newsRight">
             <form class="form-inline public_search">
                <div class="form-group">
                    <label for="exampleInputName2">权限名称:</label>
                    <input type="text" class="form-control" id="exampleInputName2" name="role_name">
                </div>
                <button type="button" class="btn submit goodBack">查询</button>
            </form>
            <div class="listBanner col-lg-12">
                <script type="text/html" id="roleList">
                    {{if roles.length > 0}}
                        {{each roles as roleList index}}
                        <div class="col-lg-2 banner">
                            <div class="top">
                                <img src="<%= image_path("bg_air.png")%>" />
                                {{if roleList.valid_flag =="1"}}
                                    <div class="pull-right status goodBack" value="{{roleList.valid_flag}}">启用</div>
                                {{else}}
                                    <div class="pull-right status badBack" value="{{roleList.valid_flag}}">禁用</div>
                                {{/if}}
                                <div class="user">{{roleList.role_name}}</div>
                                <div style="padding:0;">
                                    {{each roleList.sSubsystList as sSubsyst index}}
                                        {{if sSubsyst=="空气监测"}}
                                            <span class="list airStation">{{sSubsyst}}</span>
                                        {{else if sSubsyst=="水质监测"}}
                                            <span class="list waterStation">{{sSubsyst}}</span>
                                        {{else}}
                                            <span class="list operationStation">{{sSubsyst}}</span>
                                        {{/if}}
                                    {{/each}}
                                </div>
                            </div>
                            <div class="bottom">
                                <span class="edit cursorPointer" value="{{roleList.id}}" data-toggle="modal" data-target="#limit_edit">编辑</span>
                               <!-- 配置<div class="line"></div>
                                <span class="config cursorPointer" value="{{roleList.id}}" data-toggle="modal" data-target="#add_config">配置</span>-->
                            </div>
                        </div>
                        {{/each}}
                    {{else}}
                         <div class="col-lg-2 banner" style="line-height:160px;">暂无数据</div>
                    {{/if}}
                </script>
            </div>
            <!--分页 .yn_public_page-->
            <div class="yn_public_page">
                <div class="pageTotal pull-left">共 <a></a> 条数据,当前显示第 <small></small> 页,共 <span></span> 页</div>
                <ul class="page pull-right" maxshowpageitem="5" pagelistcount="10"  id="page"></ul>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <div class="loading">
        <div class="actingCon pcactingCon">
                <div class="img"></div>
                <p>加载中...</p>
        </div>
    </div>
     <!--增加工号-->
	<div class="modal fade" id="limit_add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="exampleModalLabel">创建角色</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" id="limit_add_form">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">角色名称:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" name="role_name" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">是否启用:</label>
                              <div class="col-xs-9">
                                <a href="javascript:" class="Radio"> <b class="hide"></b>
                                    <span class="right-radio"> <input id="optionsRadios1"
                                        type="radio" value="1" name="valid_flag" checked>是

                                </span> <span class="right-radio"> <input id="optionsRadios2"
                                        type="radio" value="0" name="valid_flag">否
                                </span>
                                </a>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">系统权限:</label>
                            <div class="col-sm-9 list">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                            <button type="button" class="btn goodBack submit">保存</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

     <!--编辑工号-->
	<div class="modal fade" id="limit_edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="exampleModalLabel">修改角色</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" id="limit_edit_form">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">角色名称:</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" name="role_name" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">是否启用:</label>
                              <div class="col-xs-9">
                                <a href="javascript:" class="Radio"> <b class="hide"></b>
                                    <span class="right-radio"> <input id="optionsRadios1"
                                        type="radio" value="1" name="valid_flag" checked>是

                                </span> <span class="right-radio"> <input id="optionsRadios2"
                                        type="radio" value="0" name="valid_flag">否
                                </span>
                                </a>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">系统权限:</label>
                            <div class="col-sm-9 list">
                             
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                            <button type="button" class="btn goodBack submit">保存</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--权限配置-->
    	<!--<div class="modal fade" id="add_config" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title center" id="exampleModalLabel">配置用户权限</h4>
                    </div>
                    <div class="modal-body content">
                        <form class="form-horizontal" id="add_config_form"
                            method="post">
                            <div class="content-outside">
                                <div class="lines form-group">
                                    <div class="line-top">
                                    </div>
                                </div>
                                <ul class="left-list list list_config">
                                </ul>
                                <div class="modal-footer" style="text-align: center;">
                                    <button type="button" class="btn submit goodBack">保存</button>
                                </div>
                            </div>
                        </form>
                    
                    </div>
                </div>
            </div>
        </div>-->

</div>
<!--空气站权限获取-->
<script type="text/html" id="list_air">
        <input type="text" name="func_code_true" class="hide">
        <input type="text" name="func_code_false" class="hide">
    {{each all_funs as listAir index}}
         <li class="che che1">
            <p>
                <input type="checkbox" value="{{listAir.id}}" /> <span>{{listAir.func_name}}</span>
                <i>{{listAir.id}}</i>
            </p>
             <ul class="che2">
                {{each listAir.son_all as listAir_child index}}
                    <li><input type="checkbox" value="{{listAir_child.id}}" />
                    <span>{{listAir_child.func_name}}</span> <i>{{listAir_child.id}}</i></li>
                {{/each}}
            </ul>
        </li>
    {{/each}}
</script>
<!--水站权限获取-->
<script type="text/html" id="list_water">
    {{each funcs as listWater index}}
         <li class="che che1">
            <p>
                <input type="checkbox" value="{{listWater.id}}" /> <span>{{listWater.func_name}}</span>
                <i>{{listWater.id}}</i>
            </p>
             <ul class="che2">
                {{each listWater.chil as listWater_child index}}
                    <li><input type="checkbox" value="{{listWater_child.id}}" />
                    <span>{{listWater_child.func_name}}</span> <i>{{listWater_child.id}}</i></li>
                {{/each}}
            </ul>
        </li>
    {{/each}}
</script>

app/views/s_role_msgs/show.html.erb
<!--角色权限查询-->
<div class="roleBox">
    <p>角色权限查询</p>
	<div id="roleRefer">
		<p>
		  <strong>角色名称:</strong>
		  <%= @s_role_msg.role_name %>
		</p>

		<p>
		  <strong>有效标志:</strong>
		  <%= @s_role_msg.valid_flag %>
		</p>
		<div class="roleBtn">
			<%= link_to '编辑', edit_s_role_msg_path(@s_role_msg),class:"btn btn-primary" %> 		
		</div>
	</div>
</div>