config/routes.rb
Rails.application.routes.draw do

  mount CookV1Api => '/api/v1'

  resources :s_subsyst_lists
  get 'user_subsyst_list' => 's_subsyst_lists#user_subsys'
  resources :sessions, only:[:new, :create, :destroy]
  resources :d_login_msgs do
    get "region_codes", on: :collection
  end

  resources :s_role_msgs 
  
  resources :ihomes

  resources :d_notice_msgs

  resources :d_login_ips #限制登陆IP

  resources :s_region_code_infos do
    get "get_ids", on: :collection
  end

  resources :windy

  resources :root_home

  resources :s_system_configs

  get "GIS_map" => "gis_map#index"

  root 'ihomes#index'

end

app/models/ihome.rb
class Ihome < ActiveRecord::Base
end

app/controllers/ihomes_controller.rb
class IhomesController < ApplicationController
  before_filter :authenticate_user
  before_action :set_ihome, only: [:show, :edit, :update, :destroy]
  # before_action :current_user

  # GET /ihomes
  # GET /ihomes.json
  def index
    @ihomes = Ihome.all
    @role_msgs =  @current_user.s_role_msg.role_name
    @s_subsyst_lists = SSubsystList.all
    ## 登录布局
    render layout: "home_iframe"
  end

  # GET /ihomes/1
  # GET /ihomes/1.json
  def show
  end

  # GET /ihomes/new
  def new
    @ihome = Ihome.new
  end

  # GET /ihomes/1/edit
  def edit
  end

  # POST /ihomes
  # POST /ihomes.json
  def create
    @ihome = Ihome.new(ihome_params)

    respond_to do |format|
      if @ihome.save
        format.html { redirect_to @ihome, notice: 'Ihome was successfully created.' }
        format.json { render :show, status: :created, location: @ihome }
      else
        format.html { render :new }
        format.json { render json: @ihome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ihomes/1
  # PATCH/PUT /ihomes/1.json
  def update
    respond_to do |format|
      if @ihome.update(ihome_params)
        format.html { redirect_to @ihome, notice: 'Ihome was successfully updated.' }
        format.json { render :show, status: :ok, location: @ihome }
      else
        format.html { render :edit }
        format.json { render json: @ihome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ihomes/1
  # DELETE /ihomes/1.json
  def destroy
    @ihome.destroy
    respond_to do |format|
      format.html { redirect_to ihomes_url, notice: 'Ihome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ihome
      @ihome = Ihome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ihome_params
      params.fetch(:ihome, {})
    end
end

app/helpers/ihomes_helper.rb
module IhomesHelper
end

app/views/ihomes/_form.html.erb
<%= form_for(@ihome) do |f| %>
  <% if @ihome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ihome.errors.count, "error") %> prohibited this ihome from being saved:</h2>

      <ul>
      <% @ihome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ihomes/edit.html.erb
<h1>Editing Ihome</h1>

<%= render 'form' %>

<%= link_to 'Show', @ihome %> |
<%= link_to 'Back', ihomes_path %>

app/views/ihomes/new.html.erb
        <!--改变部分-->
        <div id="portalsHeader">
                <div class="col-lg-12 col-sm-12 container">
                  
                    <div class="col-lg-12 col-md-12 col-sm-12 newsRight">
                        <div class="col-lg-2 banner">
                            <a href="http://172.168.10.7:3000" target="nav">
                                <img src="<%= image_path("bg_air.png")%>" />
                                <span>空气站</span>
                            </a>
                        </div>
                        <div class="col-lg-2 banner">
                            <a href="http://172.168.10.7:3020" target="nav">
                                <img src="<%= image_path("bg_water.png")%>" />
                                <span>水站</span>
                            </a>
                        </div>
                        <div class="col-lg-2 banner">
                            <a href="http://172.168.10.8:8020/SaosMgr" target="nav">
                                <img src="<%= image_path("bg_farm.png")%>" />
                                <span>智慧农业</span>
                            </a>
                        </div>
                        <div class="col-lg-2 banner">
                            <a href="http://172.168.10.7:3030" target="nav">
                                <img src="<%= image_path("bg_oper.png")%>" />
                                <span>运维</span>
                            </a>
                        </div>
                    </div>
                </div>
        </div>

app/views/ihomes/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head >
	<meta charset="UTF-8" http-equiv="Content-Type">
  <title>环境空气质量监测平台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>        
     <div id="portalsHeader">
        <div class="col-lg-12 col-sm-12 container">
            <div class="col-lg-3 col-md-3 col-sm-3 newsLeft">
                <p class="title center">8888最新消息</p>
                <div class="content">
                    <p class="news">
                        <span>1.2017-10-24 11:36:00</span>
                        <span>报警监控界面出现一般报警...</span>
                    </p>
                    <p class="news">
                        <span>1.2017-10-24 11:36:00</span>
                        <span>报警监控界面出现一般报警...</span>
                    </p>
                    <p class="news">
                        <span>1.2017-10-24 11:36:00</span>
                        <span>报警监控界面出现一般报警...</span>
                    </p>
                    <p class="news">
                        <span>1.2017-10-24 11:36:00</span>
                        <span>报警监控界面出现一般报警...</span>
                    </p>
                </div>
            </div>
            <div class="col-lg-9 col-md-9 col-sm-9 newsRight">
                <div class="col-lg-3 banner">
                    <a href="172.168.10.8">
                       <img src="<%= image_path("bg_farm.png")%>" />
                         <span>农业</span>
                    </a>
                </div>
                <div class="col-lg-3 banner">
                     <img src="<%= image_path("bg_farm.png")%>" />
                    <span>农业</span>
                </div>
                <div class="col-lg-3 banner">
                    <img src="<%= image_path("bg_farm.png")%>" />
                    <span>农业</span>
                </div>
                <div class="col-lg-3 banner">
                    <img src="<%= image_path("bg_farm.png")%>" />
                    <span>农业</span>
                </div>
            </div>
        </div>
    </div>
</body>
</html>