config/routes.rb
Rails.application.routes.draw do

  mount CookV1Api => '/api/v1'

  resources :s_subsyst_lists
  get 'user_subsyst_list' => 's_subsyst_lists#user_subsys'
  resources :sessions, only:[:new, :create, :destroy]
  resources :d_login_msgs do
    get "region_codes", on: :collection
  end

  resources :s_role_msgs 
  
  resources :ihomes

  resources :d_notice_msgs

  resources :d_login_ips #限制登陆IP

  resources :s_region_code_infos do
    get "get_ids", on: :collection
  end

  resources :windy

  resources :root_home

  resources :s_system_configs

  get "GIS_map" => "gis_map#index"

  root 'ihomes#index'

end

app/models/d_login_msg.rb
class DLoginMsg < ActiveRecord::Base
  has_secure_password

  belongs_to :s_role_msg #, foreign_key: "role_id"
  belongs_to :s_region_code, foreign_key: "group_id"
  belongs_to :s_region_code_info

  # 按名字模糊查询
  scope :by_user_name, ->(user_name){
    where("login_name like ?", "%#{user_name}%") if user_name.present?
  }

  # 按名字模糊查询
  scope :by_user_id, ->(role_id){
    where(:s_role_msg_id => role_id) if role_id.present?
  }

  def new_session
    SecureRandom.urlsafe_base64
  end
  
  def navi_bar
    self.s_role_msg.s_func_msgs.where( "root_distance = 1 and valid_flag = 0" ).order( :queue_index )
  end
  
  #### 工号所属区域及子区
  def region_codes
    @d_login_region_codes    = Array.new
    @d_login_region_codes[0] = self.s_region_code.region_code
    self.s_region_code.son_region.each do | son_region_code |
      @d_login_region_codes.push( son_region_code.region_code )
    end
    
    return @d_login_region_codes
  end
  
  
end

app/controllers/d_login_msgs_controller.rb
class DLoginMsgsController < ApplicationController
  before_filter :authenticate_user
  before_action :set_d_login_msg, only: [:show, :edit, :update, :destroy]

  # GET /d_login_msgs
  # GET /d_login_msgs.json
  def index
    @d_region_code  = SRegionCode.all #区域
    @s_region_code_info = SRegionCodeInfo.select(:id,:unit_name) #单位
    login_name = params[:login_name]
    role_id = params[:role_id]
    pageNow = params[:pageNow]
    pageSize = 10
    users = DLoginMsg.new
    @roles = SRoleMsg.where('valid_flag = 1')
    users = DLoginMsg.by_user_id(role_id).by_user_name(login_name)
    @d_login_msgs = users.page(pageNow).per(pageSize)
    @count = users.count
    s = @count%pageSize
    if s == 0
      @page = @count/pageSize
    else
      @page = (@count-s)/pageSize+1
    end 
      str = Time.now
      Rails.logger.info str.strftime("%Y-%m-%d %H:%M:%S")
    end

  # GET /d_login_msgs/1
  # GET /d_login_msgs/1.json
  def show
  end

  # GET /d_login_msgs/new
  def new
    @d_login_msg    = DLoginMsg.new
    
  end

  # GET /d_login_msgs/1/edit
  def edit
    id = params[:id]
    unless id.nil?
      @d_login_msg = DLoginMsg.find_by(:id =>id)
      @s_region_code = SRegionCode.select(:id,:region_name,:father_region_id).find_by(:id =>@d_login_msg.group_id)
      @father_region_code = SRegionCode.select(:id,:region_name).find_by(:id =>@s_region_code.father_region_id)
      @code_info = SRegionCodeInfo.select(:id,:unit_name).find_by(:id =>@d_login_msg.s_region_code_info_id)
    end
  end

  # POST /d_login_msgs
  # POST /d_login_msgs.json
  def create
    retCode = true
    @d_login_msg = DLoginMsg.new(d_login_msg_params)
    # 写日志
    wLoginOpr = WLoginOpr.new
    wLoginOpr.op_code   = "d_login_msgs|create"
    wLoginOpr.op_time   = Time.now.to_s
    wLoginOpr.login_no  = current_user.login_no
    wLoginOpr.ip_addr   = current_user.ip_address
    wLoginOpr.op_note   = "增加工号"
    wLoginOpr.op_describe = "增加工号，工号名称：" + d_login_msg_params[:login_name]
    
    login_no = d_login_msg_params[:login_no]
    login = DLoginMsg.where('login_no = ?',login_no)
    if login.blank?
      @d_login_msg.transaction do
        retCode = @d_login_msg.save
        retCode = wLoginOpr.save if retCode
      end

      respond_to do |format|
        if retCode
          format.html { redirect_to "/d_login_msgs" }
          format.json { render json:{'status': '新增成功'}}
        else
          format.html { render :new }
          format.json { render json: @d_login_msg.errors, status: :unprocessable_entity }
        end
      end
    else       
      render json:{'status': '工号重复'}
    end 
  end

  # PATCH/PUT /d_login_msgs/1
  # PATCH/PUT /d_login_msgs/1.json
  def update
    retCode = true
    d_login_msg = DLoginMsg.find(params[:id])    
     # 写日志
    wLoginOpr = WLoginOpr.new
    wLoginOpr.op_code   = "d_login_msgs|update"
    wLoginOpr.op_time   = Time.now.to_s
    wLoginOpr.login_no  = current_user.login_no
    wLoginOpr.ip_addr   = current_user.ip_address
    wLoginOpr.op_note   = "编辑工号"
    wLoginOpr.op_describe = "编辑工号，" + "工号编码：" + d_login_msg.login_no + ", 工号名称：" + d_login_msg.login_name
    
    @d_login_msg.transaction do
      retCode = @d_login_msg.update(d_login_msg_params)
      retCode = wLoginOpr.save if retCode
    end
    
    respond_to do |format|
      if retCode
        format.html { redirect_to "/d_login_msgs" }
        format.json { render json:{'status': '1'} }
      else
        format.html { render :edit }
        format.json { render json: @d_login_msg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /d_login_msgs/1
  # DELETE /d_login_msgs/1.json
  def destroy
    @d_login_msg.destroy
    respond_to do |format|
      format.html { redirect_to d_login_msgs_url, notice: 'D login msg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #GET /d_login_msgs/region_codes
  def region_codes
      father_id = params[:father_region_id]
      @s_region_code = SRegionCode.where(:father_region_id =>father_id)
      render json: {d_region_code: @s_region_code}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_d_login_msg
      @d_login_msg = DLoginMsg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def d_login_msg_params
      params.require(:d_login_msg).permit( :login_no, :login_name, :group_id, :s_role_msg_id, :password, :password_confirmation, :password_digest, :valid_flag, :valid_begin, :valid_end, :ip_address, :describe ,:s_region_code_info_id)
    end
end

app/views/d_login_msgs/_form.html.erb
<%= form_for(@d_login_msg) do |f| %>
  <% if @d_login_msg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@d_login_msg.errors.count, "error") %> prohibited this d_login_msg from being saved:</h2>

      <ul>
      <% @d_login_msg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logis123n_no %><br>
    <%= f.text_field :login_no %>
  </div>
  <div class="field">
    <%= f.label :login_name %><br>
    <%= f.text_field :login_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  # <div class="field">
  #   <%= f.label :group_id %><br>
  #   <%= f.text_field :group_id %>
  # </div>
  # <div class="field">
  #   <%= f.label :role_id %><br>
  #   <%= f.number_field :role_id %>
  # </div>
  <div class="field">
    <%= f.label :valid_flag %><br>
    <%= f.text_field :valid_flag %>
  </div>
  <div class="field">
    <%= f.label :valid_begin %><br>
    <%= f.date_select :valid_begin %>
  </div>
  <div class="field">
    <%= f.label :valid_end %><br>
    <%= f.date_select :valid_end %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="field">
    <%= f.label :describe %><br>
    <%= f.text_field :describe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/d_login_msgs/edit.html.erb
<!--编辑工号-->
<div id="edit">
    <p><span class="glyphicon glyphicon-edit"></span>编辑工号</p>
    <%= form_for(@d_login_msg) do |f| %>
    <% if @d_login_msg.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@d_login_msg.errors.count, "error") %> prohibited this d_login_msg from being saved:</h2>

        <ul>
            <% @d_login_msg.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <div class="field">
        <label class="col-xs-4 fieldChild control-label">用户编码：</label>
        <div class="col-xs-8">
            <%= f.text_field :login_no,class:"form-control",required:"true" %>
        </div>
    </div>
    <div class="field">
        <label class="col-xs-4 fieldChild control-label">用户名：</label>
        <div class="col-xs-8">
            <%= f.text_field :login_name,class:"form-control",required:"true" %>
        </div>
    </div>
    
    <div class="field">
        <label class="col-xs-4 fieldChild control-label">是否有效：</label>
		<b class="hide validFlag"><%= @d_login_msg.valid_flag %></b>
        <div class="col-xs-8">
			<%= f.radio_button "valid_flag","1",class:"valid" %>
			<label style="float: left;">有效</label>
			<%= f.radio_button "valid_flag","0",class:"flag" %>
			<label style="float: left;margin: 0;">无效</label>
		</div>
    </div>
    <div class="field">
        <label class="col-xs-4 fieldChild control-label">有效开始日期：</label>
        <div class="col-xs-8">
            <%= f.text_field :valid_begin,class:"some_class",required:"true" %>
        </div>
    </div>
    <div class="field">
        <label class="col-xs-4 fieldChild control-label">有效结束日期：</label>
        <div class="col-xs-8">
            <%= f.text_field :valid_end,class:"some_class",required:"true" %>
        </div>
    </div>
    <div class="field">
        <label class="col-xs-4 fieldChild control-label">Ip地址：</label>
        <div class="col-xs-8">
            <%= f.text_field :ip_address,class:"form-control unable" %>
        </div>
    </div>
    <div class="describeBox">
        <label class="col-xs-2 fieldChild control-label">描述：</label>
        <div class="col-xs-10">
            <%= f.text_area :describe,class:"describe col-xs-12" %>
        </div>
    </div>
    <div class="editNo">
        <%= f.submit "保存",class:"btn btn-primary  col-xs-offset-5" %>
        <%= link_to '返回', d_login_msgs_path,class:"btn btn-primary back"  %>
    </div>
    <% end %>
</div>

<script>
$(function(){
	/*有效的标志*/
	if($(".validFlag").text() == '1'){
		$(".valid").prop("checked","checked");
		$(".flag").removeAttr("checked");
	}else{
		$(".flag").prop("checked","checked");
		$(".valid").removeAttr("checked");
	}
	$(".choice").focus(function(){
	    this.blur();
	});
	
	$(".unable").focus(function(){
		this.blur();
	});
	
	
	for(var j=0;j<$("#valid_flag option").length;j++){
		if($("#valid_flag option").eq(j).text() == '1'){
			$("#valid_flag option").eq(j).html("有效");
		}else{
			$("#valid_flag option").eq(j).html("无效");
		}
	}
	/*日期*/
	var time = new Date();
	var year = time.getFullYear();
	$('.some_class').datetimepicker({
		format:"Y-m-d",
		minDate:year+'-01-01',
		maxDate: year+'-12-31',
		todayButton:true,
		timepicker:false
	})
	var myMonth = time.getMonth()+1
	var myDate = time.getDate()-1
	//站点
	$('.choose').click(function(){
			$('#search-station .choose-site').show()
		})
		$('#search-station .tab-top span').click(function(){
			var $index = $(this).index()
			$('#search-station .choose-site .tab-station').eq($index-1).show().siblings().hide()
			$(this).css('background','#fff').siblings().css('background','')
		})
		$('#search-station .tab-top span').eq(0).click(function(){
			$('#search-station .choose-site .tab-station').show()
		})
		
		$('#search-station .station-btn .btn-sure').click(function(){
			$('#search-station .choose-site').hide()
			if($('#search-station .choose-site  .radios:checked')){
				var text=[];
				var textid=[];
				$('#search-station  .radios:checked').siblings('small').each(function(){
					text.push(this.innerHTML)
				})
				$('#search-station  .radios:checked').siblings('a').each(function(){
					textid.push(this.innerHTML)
				})
				var allText = text.join(',')
				var textid=textid.join(',')
				$('.chooseBox').val(allText)
				$('.choice').val(textid)
			}else{
				$('#day-table .search-once .controll-station').val('')
				$('#day-table .search-once .selId').val('')
			}
		})
		$('#search-station .choose-site .tab-station').each(function(i){
			$(this).find('p span').click(function(){
				var check;
				$('#search-station .choose-site .tab-station').eq(i).find('.list-city input').each(function(){
					if($(this).prop('checked')==false){
						check='false';
						return false
					}else{
						check='true'
					}
				})
				if(check=='true'){
					$('#search-station .choose-site .tab-station').eq(i).find('.list-city input').prop('checked',true)
				}else{
					$('#search-station .choose-site .tab-station').eq(i).find('.list-city input').prop('checked',false)
				}
			})
		})	
		$('#search-station .station-btn .btn-cancel').click(function(){
			$('#search-station .choose-site').hide()
		})
})	
</script>

app/views/d_login_msgs/edit_passwd.html.erb
<div id="reset" class=" reg-container">
	<div class="resetPassword">
		<span class="glyphicon glyphicon-edit"></span>重置密码
	</div>
	<%= form_for(@d_login_msg,method:'put') do |f| %>
		<% if @d_login_msg.errors.any? %>
			<div id="error_explanation">
			  <h2><%= pluralize(@d_login_msg.errors.count, "error") %> prohibited this d_login_msg from being saved:</h2>
			  <ul>
			  <% @d_login_msg.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			  <% end %>
			  </ul>
			</div>
		<% end %>
		<%= f.text_field :login_no,class:"hide" %>
		<%= f.text_field :login_name,class:"hide" %>
		<div class="form-group">
			<label class="col-xs-2 control-label pwd" id="npwd" for="password">新密码：</label>
			<div class="col-xs-5">
				<%= f.password_field :password,id:"password",class:"form-control",autofocus:"true",placeholder:"请输入密码",required:"true",pattern:"^[a-zA-Z0-9]{3,16}$" %>
				<label id="passwordTip" class="warn control-default">请输入3至16位的英文或数字.</label>
			</div>
			
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label pwd" id="pwds" for="password_confirmation">确认新密码：</label>
			<div class="col-xs-5">
				<%= f.password_field :password_confirmation,id:"password_confirmation",class:"form-control",placeholder:"请输入新密码" ,required:"true",pattern:"^[a-zA-Z0-9]{3,16}$" %>
				<label id="password_confirmationTip" class="warn hide control-default">请输入3至16位的英文或数字.</label>
			</div>
			
		</div>
		<div class="form-group">
			<div class="actions submit col-xs-5 col-xs-offset-2">
				<%= f.submit "提交",id:"pwdSubmit",type:"submit",class:"btn btn-primary btn-block",disabled:"true" %>
				<%= link_to '返回', d_login_msgs_path,class:"btn btn-primary back"  %>
			</div>
		</div>
	<% end %>
</div>
<script>
    var passWd = document.getElementById("password");
    var passWdTip = document.getElementById("passwordTip");
    passWd.onfocus = function(){
        passWdTip.className = "col-xs-5 show control-default";
        passWdTip.firstChild.nodeValue = "请输入3至16位的英文或数字."
    };
    passWd.onblur = function(){
        if(passWd.validity.valid){
            passWdTip.className = "col-xs-5 show control-success";
            passWdTip.firstChild.nodeValue = "密码正确."
        }else if(passWd.validity.valueMissing){
            passWdTip.className = "col-xs-5 show control-error";
            passWdTip.firstChild.nodeValue = "密码不能为空."
        }else if(passWd.validity.patternMismatch){
            passWdTip.className = "col-xs-5 show control-error";
            passWdTip.firstChild.nodeValue = "密码输入有误."
        }
    };
    var affirmPwd= document.getElementById("password_confirmation");
    var affirmPwdTip = document.getElementById("password_confirmationTip");
    affirmPwd.onfocus = function(){
        affirmPwdTip.className = "col-xs-5 show control-default";
        affirmPwdTip.firstChild.nodeValue = "请输入3至16位的英文或数字."
    };
    affirmPwd.onblur = function(){
        if(affirmPwd.validity.valid){
            if(passWd.value!=null&&passWd.value==affirmPwd.value) {
                affirmPwdTip.innerHTML = "两次密码相同可以使用";
				affirmPwdTip.className="col-xs-5 show control-success";
                document.getElementById("pwdSubmit").disabled = false;
			}else{
                affirmPwdTip.innerHTML="两次密码不相同";
                affirmPwdTip.className="col-xs-5 show control-error";
                document.getElementById("pwdSubmit").disabled = true;
			}
        }else if(affirmPwd.validity.valueMissing){
            affirmPwdTip.className = "col-xs-5 show control-error";
            affirmPwdTip.firstChild.nodeValue = "密码不能为空."
        }else if(affirmPwd.validity.patternMismatch){
            affirmPwdTip.className = "col-xs-5 show control-error";
            affirmPwdTip.firstChild.nodeValue = "密码输入有误."
        }  
    };
</script>

app/views/d_login_msgs/new.html.erb
<div id="add" class="overflows">
	<div class="addno">
		<span class="glyphicon glyphicon-edit"></span>增加工号
	</div>
	<%= form_for(@d_login_msg) do |f| %>
	    <% if @d_login_msg.errors.any? %>
			<div id="error_explanation">
			  <h2><%= pluralize(@d_login_msg.errors.count, "error") %> prohibited this d_login_msg from being saved:</h2>
			  <ul>
			  <% @d_login_msg.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			  <% end %>
			  </ul>
			</div>
	    <% end %>
		<div class="form-group">
			<label class="col-xs-2 control-label" id="uname" for="login_no">工号编码:</label>
			<div class="col-xs-8">
				<%= f.text_field :login_no,id:"login_no",class:"form-control",required:"true",autofocus:"true", placeholder:"请输入工号编码",pattern:"^[a-zA-Z0-9]{2,16}$"%>
				<label id="login_no_Tip" class="warn col-xs-5 control-default">请输入2至16位的英文或数字.</label>
			</div>
			
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label" id="uname1" for="login_name">工号名称:</label>
			<div class="col-xs-8">
				<%= f.text_field :login_name,id:"login_name",required:"true",class:"form-control",placeholder:"请输入工号名",pattern:"^[\u4e00-\u9fa5]{2,8}$" %>
				<label id="login_nameTip" class="warn col-xs-5 hide control-default">请输入2至8位汉字.</label>
		   </div>
			
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label" id="upwd" for="password">密码:</label>
			<div class="col-xs-8">
			   <%= f.password_field :password,id:"password",required:"true",class:"form-control",placeholder:"请输入密码",pattern:"^[a-zA-Z0-9]{2,16}$" %>
			   <label id="passwordTip" class="warn col-xs-5 hide control-default">请输入2至16位的数字.</label>
			</div>
			
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label" id="upwd1" for="password_confirmation">确认密码:</label>
			<div class="col-xs-8">
				 <%= f.password_field :password_confirmation,id:"password_confirmation",required:"true",class:"form-control",placeholder:"请输入密码",pattern:"^[a-zA-Z0-9]{2,16}$" %>
				 <label id="password_confirmationTip" class="warn col-xs-5 hide control-default">请输入2至16位的数字.</label>
			</div>
			
		</div>
	    <div class="form-group">
			<label class="col-xs-2 control-label" for="group_id">区域归属:</label>
			<div class="col-xs-8 selectTime">
				<div class="col-xs-4 areaAffiliation">
					<input class="form-control area" required="true" pattern="^([\u4e00-\u9fa5]{2,16})$" placeholder="请点击选择勾选区域归属" />
					<%= f.text_field :group_id,class:"chooseBox hide" %>
				</div>
				<div class="col-xs-2 choice">
					<span class="btn btn-primary">选择</span>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label" for="role_id">角色:</label>
			<div class="col-xs-8" id="roleId">
				<%= select_tag "role_id", options_from_collection_for_select(@s_role_msgs, "id", "role_name"),{name:"d_login_msg[s_role_msg_id]"} %>
			</div>
			<label id="role_idTip" class="warn col-xs-5 hide control-default">请输入你的角色编码</label>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label" for="valid_flag">有效标志:</label>
			<div class="col-xs-8" id="validLogo">
				
				<%= select_tag "d_login_msg[valid_flag]", options_for_select([["有效","1"], ["无效","0"]]) %>
			</div>
			<label id="valid_flagTip" class="warn col-xs-5 hide control-default">请输入你的有效标志</label>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label" for="valid_begin">有效开始时间:</label>
			<div class="col-xs-8">
				<%= f.text_field :valid_begin,id:"valid_begin",class:"form-control some_class",required:"true",placeholder:"请输入有效开始时间" %>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label" for="valid_end">有效结束时间:</label>
			<div class="col-xs-8 selectTime">
				<%= f.text_field :valid_end,id:"valid_end",class:"form-control some_class",required:"true",placeholder:"请输入有效结束时间" %>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label" for="describe">描述:</label>
			<div class="col-xs-8">
				<%= f.text_field :describe,class:"form-control"%>
			</div>
		</div>
		<div class="form-group">
			<div class="submit col-xs-5">
				<%= f.submit "注册",class:"form-control btn btn-primary btn-block"%>
				<%= link_to '返回', d_login_msgs_path,class:"btn btn-primary back"  %>
			</div>
		</div>
	<% end %>
	<div class="addEdit col-xs-5 col-xs-offset-2">
		<div class="sBtn">
			
		</div>
	</div>
</div>

app/views/d_login_msgs/show.html.erb
<!--工号查询-->
<div id="check">
	<div class="numberQuery">
		<span class="glyphicon glyphicon-search"></span>工号查询
	</div>
	<p>
	  <strong>用户编码:</strong>
	  <%= @d_login_msg.login_no %>
	</p>
	<p>
	  <strong>用户名:</strong>
	  <%= @d_login_msg.login_name %>
	</p>
	# <p>
	#   <strong>所在区域:</strong>
	#   <%= @d_login_msg.s_region_code.region_name %>
	# </p>
	# <p>
	#   <strong>角色:</strong>
	#   <%= @d_login_msg.s_role_msg.role_name %>
	# </p>
	<p>
	  <strong>有效的标志:</strong>
	  <%= @d_login_msg.valid_flag %>
	</p>
	<p>
	  <strong>有效开始日期:</strong>
	  <%= @d_login_msg.valid_begin %>
	</p>
	<p>
	  <strong>有效结束日期:</strong>
	  <%= @d_login_msg.valid_end %>
	</p>
	<p>
	  <strong>Ip地址:</strong>
	  <%= @d_login_msg.ip_address %>
	</p>
	<p>
	  <strong>描述:</strong>
	  <%= @d_login_msg.describe %>
	</p>
	<div class="editBox">			
		<div class="sBtn">
			<%= link_to '重置密码', edit_d_login_msg_path(@d_login_msg, reset_passwd:"Yes"),class:"btn btn-primary" %>
		</div>
		<div class="sBtn">
			<%= link_to '编辑', edit_d_login_msg_path(@d_login_msg),class:"btn btn-primary" %> 
		</div>
		<div class="sBtn">
			<%= link_to '返回', d_login_msgs_path,class:"btn btn-primary" %>
		</div>
	</div>
</div>