config/routes.rb
Rails.application.routes.draw do

  mount CookV1Api => '/api/v1'

  resources :s_subsyst_lists
  get 'user_subsyst_list' => 's_subsyst_lists#user_subsys'
  resources :sessions, only:[:new, :create, :destroy]
  resources :d_login_msgs do
    get "region_codes", on: :collection
  end

  resources :s_role_msgs 
  
  resources :ihomes

  resources :d_notice_msgs

  resources :d_login_ips #限制登陆IP

  resources :s_region_code_infos do
    get "get_ids", on: :collection
  end

  resources :windy

  resources :root_home

  resources :s_system_configs

  get "GIS_map" => "gis_map#index"

  root 'ihomes#index'

end

app/models/s_subsyst_list.rb
class SSubsystList < ActiveRecord::Base
  # has_many :s_role_systs
  belongs_to :s_role_msg

  
  #has_many :s_role_subsysts
  #has_many :s_role_msg, :through =>  :s_role_subsysts
  has_many :s_role_funcs ,foreign_key: 's_func_msg_id'
  has_many :s_role_msg, :through =>  :s_role_funcs


  # 应急报警  "air_police"
  # 水质监测  "water_monitor"
  # 污染源监测 "polluter_monitor"
  # 空气监测 "air_monitor"
  # 运维管理 "air_queen"
end

app/controllers/s_subsyst_lists_controller.rb
class SSubsystListsController < ApplicationController
  before_filter :authenticate_user
  before_action :set_s_subsyst_liste, only: [:show, :edit, :update, :destroy]

  # GET /s_subsyst_listes
  # GET /user_subsys_lists.json
  def user_subsys
    
    # 业务系统链接
    @s_subsyst_lists = current_user.s_role_msg.s_subsyst_list
    @s_subsyst_lists.each do |s_subsyst_list|
        s_subsyst_list.sys_url = s_subsyst_list.sys_url + "?session=" + session[:session_code].to_s 
    
    end
    @subsyst_list = SSubsystList.where.not(:sys_name =>'发布公告')
    respond_to do |format|
      #format.html { redirect_to "/sessions/new", notice: 'Session was successfully destroyed.' }
      format.json { render :user_subsyst, status: :ok }
    end
  end
  
  # GET /s_subsyst_listes
  # GET /s_subsyst_listes.json
  def index
    @s_subsyst_lists = SSubsystList.all
  end

  # GET /s_subsyst_listes/1
  # GET /s_subsyst_listes/1.json
  def show
  end

  # GET /s_subsyst_listes/new
  def new
    @s_subsyst_list = SSubsystList.new
  end

  # GET /s_subsyst_listes/1/edit
  def edit
  end

  # POST /s_subsyst_listes
  # POST /s_subsyst_listes.json
  def create
    @s_subsyst_list = SSubsystList.new(s_subsyst_list_params)

    respond_to do |format|
      if @s_subsyst_liste.save
        format.html { redirect_to @s_subsyst_list, notice: 'S subsyst liste was successfully created.' }
        format.json { render :show, status: :created, location: @s_subsyst_list }
      else
        format.html { render :new }
        format.json { render json: @s_subsyst_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /s_subsyst_listes/1
  # PATCH/PUT /s_subsyst_listes/1.json
  def update
    respond_to do |format|
      if @s_subsyst_liste.update(s_subsyst_list_params)
        format.html { redirect_to @s_subsyst_list, notice: 'S subsys liste was successfully updated.' }
        format.json { render :show, status: :ok, location: @s_subsyst_list }
      else
        format.html { render :edit }
        format.json { render json: @s_subsyst_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /s_subsyst_listes/1
  # DELETE /s_subsyst_listes/1.json
  def destroy
    @s_subsyst_liste.destroy
    respond_to do |format|
      format.html { redirect_to s_subsyst_lists_url, notice: 'S subsys liste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_s_subsyst_list
      @s_subsyst_list = SSubsystList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def s_subsyst_liste_params
      params.require(:s_subsyst_list).permit(:sys_name, :sys_url, :mark)
    end
end

app/views/s_subsyst_lists/_form.html.erb
<%= form_for(@s_subsys_list) do |f| %>
  <% if @s_subsys_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@s_subsys_list.errors.count, "error") %> prohibited this s_subsys_liste from being saved:</h2>

      <ul>
      <% @s_subsys_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sys_name %><br>
    <%= f.text_field :sys_name %>
  </div>
  <div class="field">
    <%= f.label :sys_url %><br>
    <%= f.text_field :sys_url %>
  </div>
  <div class="field">
    <%= f.label :mark %><br>
    <%= f.text_field :mark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/s_subsyst_lists/edit.html.erb
<h1>Editing S Subsys List</h1>

<%= render 'form' %>

<%= link_to 'Show', @s_subsys_list %> |
<%= link_to 'Back', s_subsys_lists_path %>

app/views/s_subsyst_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing S Subsys Listes</h1>

<table>
  <thead>
    <tr>
      <th>Sys name</th>
      <th>Sys url</th>
      <th>Mark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @s_subsys_lists.each do |s_subsys_liste| %>
      <tr>
        <td><%= s_subsys_liste.sys_name %></td>
        <td><%= s_subsys_liste.sys_url %></td>
        <td><%= s_subsys_liste.mark %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New S subsys liste', new_s_subsys_list_path %>

app/views/s_subsyst_lists/new.html.erb
<h1>New S Subsys List</h1>

<%= render 'form' %>

<%= link_to 'Back', s_subsys_lists_path %>

app/views/s_subsyst_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sys name:</strong>
  <%= @s_subsys_list.sys_name %>
</p>

<p>
  <strong>Sys url:</strong>
  <%= @s_subsys_list.sys_url %>
</p>

<p>
  <strong>Mark:</strong>
  <%= @s_subsys_list.mark %>
</p>

<%= link_to 'Edit', edit_s_subsys_list_path(@s_subsys_liste) %> |
<%= link_to 'Back', s_subsys_lists_path %>